spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${APP_AWS_RDS_HOST:localhost}:${APP_AWS_RDS_PORT:5432}/${APP_AWS_RDS_DATABASE:transactionsdb}}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${APP_AWS_RDS_USERNAME:transaction_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${APP_AWS_RDS_PASSWORD:transaction_password}}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.h2.console.enabled=false
server.forward-headers-strategy=framework
server.shutdown=graceful

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

app.aws.region=${APP_AWS_REGION:}
app.aws.s3-bucket=${APP_AWS_S3_BUCKET:}
app.aws.rds-host=${APP_AWS_RDS_HOST:}
app.aws.rds-port=${APP_AWS_RDS_PORT:5432}
app.aws.rds-database=${APP_AWS_RDS_DATABASE:}
app.aws.secrets-manager-secret-name=${APP_AWS_SECRET_NAME:}
app.aws.load-balancer-dns=${APP_AWS_LOAD_BALANCER_DNS:}
